// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkcqrrekcxurunybwcyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrY3FycmVrY3h1cnVueWJ3Y3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjEwNjcsImV4cCI6MjA2Njg5NzA2N30.xFa8bWo6WRqyBfyhHoKG5XS-B160kf5-ncWihDyf54k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});